# Generated by Django 5.0.7 on 2024-07-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_description',
            field=models.TextField(default='sss', max_length=300),
        ),
    ]
