# Generated by Django 5.0.7 on 2024-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_alter_article_created_at_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/Article'),
        ),
    ]
