# Generated by Django 5.0.7 on 2024-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
