# Generated by Django 4.1.13 on 2024-07-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.ForeignKey(default='نویسنده', on_delete=django.db.models.deletion.SET_DEFAULT, to='Accounts.rank'),
        ),
    ]
