# Generated by Django 4.1.13 on 2024-07-18 13:10

import Accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.ForeignKey(default=Accounts.models.get_default_rank, on_delete=django.db.models.deletion.SET_DEFAULT, to='Accounts.rank'),
        ),
    ]
