# Generated by Django 5.0.7 on 2024-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_account_bio_alter_account_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(upload_to='images/profile_pictures'),
        ),
    ]
